baseURL = "https://georgechang.io/"
languageCode = "en-us"
title = "georgechang.io"
theme = "gc"
summarylength = 10
enableEmoji = true

googleAnalytics = ""

[author]
  givenName = "George"
  familyName = "Chang"
  displayName = "George Chang"

[permalinks]
  posts = "/posts/:year/:slug"

[menu]
  [[ menu.social ]]
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class='fa fa-twitter'></i>"
  url = "https://twitter.com/georgechang"
  weight = 100

  [[ menu.social ]]
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "<i class='fa fa-linkedin'></i>"
  url = "https://www.linkedin.com/in/georgechang/"
  weight = 200
  
  [[ menu.social ]]
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fa fa-github'></i>"
  url = "https://github.com/georgechang/"
  weight = 300

[markup]
  [markup.highlight]
    tabWidth = 2
    style = "native"

  [markup.goldmark.renderer]
    unsafe= true