baseURL = ""
languageCode = "en-us"
title = "georgechang.io"
summarylength = 10
enableEmoji = true

googleAnalytics = ""

[author]
  givenName = "George"
  familyName = "Chang"
  displayName = "George Chang"

[permalinks]
  posts = "/posts/:year/:slug"

[menu]
  [[ menu.social ]]
  identifier = "twitter"
  name = "Twitter"
  pre = "twitter"
  url = "https://twitter.com/georgechang"
  weight = 100

  [[ menu.social ]]
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/georgechang/"
  weight = 200
  
  [[ menu.social ]]
  identifier = "github"
  name = "GitHub"
  pre = "github"
  url = "https://github.com/georgechang/"
  weight = 300

[markup]
  [markup.highlight]
    tabWidth = 2
    style = "native"
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true