name: Azure Storage CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Hugo
        run: brew install hugo
      - name: Run npm install
        run: npm install
      - name: Run Hugo
        run: hugo --minify
        env:
          NODE_ENV: production
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch --account-name gcblog -s ./public -d '$web'
